language: java
script: "./gradlew --stacktrace --info :bintrayUploadAll"
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: dJyzhUG9+viWX2zWf/BmkBfAmk0YmfxZTw2aXI+0hT56NnU97vBZPilk5/BgUDRyaLvgeKczfi8LzcMJdsC+R4nbmmxn97DvRPbNgUoACfFNsF0MPXkwPoazHLmWpTS7YZM5jk3NGW+EcTpMAsCJ0YiAaBl8Fu1gmhWXZWDe1prAXpfH6rIivwGgDqY/mzJ6t9TpR52VM2dYpnm6CCVDPQ3j1QUwcZsRPgnZaivZeBtouvXibfynJXoLtciNYmdOed/71CoQI3o/5P4y/RvEhyHdPBMOoMtjgiVyirSJZ4FUU6/z747Qx5l1YG1UmLwJ+a3NmKZLQdcZ5TKRxT2EXI/qXsl94SS4c8aqi7PRWU0cdgeE9iMZUj+/GDUFcmUrmQtFZXhtvSZ3eB5rxJnwh0FeL8T7BV6CV8ykJOn5hSj5mpkbWCsIlHzjA6dCFqeGzc6V+yD3OVWQi/nd5FXc6IutBY4Zd49Lvzak0YhgLsbKvW0YZFO0KiG/Af4zcZHgc0YXuFQD9LdvDQFyR0O68ShlUQHVDYlyEigS0cqVxRIBZdn68s6qgO8VSI2B9r3c0w24HeLSq+3h/95g1Ys/A4o+xoTLsO17Frg03sGwSrPw6wedY1PyAtHfb7P3+geK/gQdrNQA9oDUFJsF6twagkLQIyqkK0XYdpr2I/IqS7M=
  matrix:
    secure: XwWq7uy9gqo7l6iu/oUmKxMaGT0/is6m2afv0HqKQUSm67gjV85FOEnkQgF536omXfYuXXERmknh9TWX9z/X0V6czPsIcY5uDIkJm+ocYYilxrO16YuQoZjDxifm0LxpSTRuqQgux9CkX6RgSmJ/wsrJn8SqsZRpp/wWTOFmx+GsqgsiL9TOAcXaT8Thgdi69garC0RDoPdD7y+sC3xj6BpbmHPuBYMg4/shYxOyfUwL1Oqm974zgWJUD3/YsvhHwmzJTcMQ8T9xNqsAydve5kTzw+PvohDlNwmEOOPgcNiMYxeAoC6jFIxXYTcbQQhinfMLrn1OjHHMzepcM9DswANnpqGzd9uaPSNOgKnzZRvldwWubAfNOf2nVEPvtRDcJp9CZIKbHoz/WYTX53k4E8aLc2G8XYP8aLCqksfue9MNrA75RzlPSpYSTlYVNgEx6OR9qYxWws4D0vZAoI0esGqXczQJkae1wJnxs8M5L5U/j+t5IwBjIRrznBQctMeZAO3DlnXC+vI+ZtN7dA+FyczY/RR+Wx9Hn/un3JMzNANlcGTxe5fHtJwgZfVK6BsUOezUtm0nmM71ggj6JKBgVkURCJY5HomafWCWdVXjO8zu8uSJdeL5QZPG5aQFUXa15uGzJH0CdBL3mC/HVeMx1g8CPz70zprIrHFNxnSrBEE=
